server:
  port: 8180

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frames?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  typeAliasesPackage: wang.doug.frame.vo
  mapperLocations: classpath:mapper/*.xml




